### ISSUE TITLE
mergetiles job failed on rocce because it ran out of memory

### ISSUE THREAD

**Issue by coleslaw481** [CRBS/chmutil#49]
A job on rocce failed cause it ran out of memory on mergetiles.py:

```Bash
2017-07-23 17:52:22,722 ERROR (11321) chmutil.mergetiles Caught exception
Traceback (most recent call last):
  File "/home/rdrigo/miniconda2/bin/mergetiles.py", line 95, in main
    theargs.suffix)
  File "/home/rdrigo/miniconda2/bin/mergetiles.py", line 53, in _merge_image_tiles
    merged = sim.merge_images(im_list)
  File "/home/rdrigo/miniconda2/lib/python2.7/site-packages/chmutil/image.py", line 42, in merge_images
    merged = self._merge_two_images(merged, entry)
  File "/home/rdrigo/miniconda2/lib/python2.7/site-packages/chmutil/image.py", line 58, in _merge_two_images
    b=image2)
  File "/home/rdrigo/miniconda2/lib/python2.7/site-packages/PIL/ImageMath.py", line 265, in eval
    out = builtins.eval(expression, args)
  File "<string>", line 1, in <module>
  File "/home/rdrigo/miniconda2/lib/python2.7/site-packages/PIL/ImageMath.py", line 232, in imagemath_max
    return self.apply("max", self, other)
  File "/home/rdrigo/miniconda2/lib/python2.7/site-packages/PIL/ImageMath.py", line 88, in apply
    out = Image.new(mode or im1.mode, im1.size, None)
  File "/home/rdrigo/miniconda2/lib/python2.7/site-packages/PIL/Image.py", line 2154, in new
    return Image()._new(core.new(mode, size))
MemoryError
2017-07-23 17:52:23,456 INFO (11318) chmutil.core Process 11320 exited with code: 2
```

The job was merging 71 tiles of size 31237x29138 pixels. To remedy this, need to estimate memory needed by merge and add the following to the -l line in runmerge.rocce configuration file:

```Bash
h_vmem=XXG,virtual_free=XXG
```
Where **XX** is number of gigabytes of ram needed. This is only needed on rocce since the queue places multiple user jobs on a node. Comet should be okay since a job gets an entire node with 128 gigabytes of ram.

**Comment by coleslaw481** [comment]
Increased memory from 10G to 20G and added virtual_free constraint
