### ISSUE TITLE
.DS_Store in input images directory causes IOError in createchmjob.py

### ISSUE THREAD

**Issue by coleslaw481** [CRBS/chmutil#50]
$ createchmjob.py chmimages model mychm --disablechmhisteq --cluster rocce --chmbin /data/churas/chm_s22.img
2017-07-24 16:46:15,539 ERROR chmutil.image Skipping file unable to open /data/scratch/churastest/chmimages/.DS_Store
Traceback (most recent call last):
  File "/home/churastest/miniconda2/lib/python2.7/site-packages/chmutil/image.py", line 382, in get_input_image_stats
    im = Image.open(fp)
  File "/home/churastest/miniconda2/lib/python2.7/site-packages/PIL/Image.py", line 2519, in open
    % (filename if filename else fp))
IOError: cannot identify image file '/data/scratch/churastest/chmimages/.DS_Store'
2017-07-24 16:46:15,560 ERROR chmutil.image Caught exception attempting to close image
Traceback (most recent call last):
  File "/home/churastest/miniconda2/lib/python2.7/site-packages/chmutil/image.py", line 391, in get_input_image_stats
    im.close()
AttributeError: 'NoneType' object has no attribute 'close'
Run this to submit job
/home/churastest/miniconda2/bin/checkchmjob.py "/data/scratch/churastest/mychm" --submit
[churastest@login-0-0 churastest]$ ls -la chmimages/.DS_Store
-rw-r--r-- 1 churastest churastest 6148 Jul 24 16:40 chmimages/.DS_Store
[churastest@login-0-0 churastest]$ file chmimages/.DS_Store

**Comment by coleslaw481** [comment]
This isn't actually a bug. The code is just logging the problem as it is supposed to. Maybe logging should just output a single error line unless debug mode level is set in which case an exception log message should be output.

**Comment by coleslaw481** [comment]
Decided to leave as is for now.
